# Generated by Django 4.0.1 on 2022-01-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='users.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='owners',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
