# Generated by Django 4.0.1 on 2022-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
